"""Say how plausible a points swing is, using this league's own history.

A verdict that rests on the total-points tiebreaker is not a bare fact -- it
holds only while the scoring holds. Rather than hide that behind an
"undetermined" bucket, state the dependency and how big the swing would have to
be, measured against what this league has actually produced.

Thresholds come from score_thresholds.json, regenerated by
tools/derive_score_thresholds.py. They are per weeks-remaining because a points
gap is only a single-week question when one week is left: both teams keep
scoring, so what matters is the differential across all the weeks that remain.
"""

import json
import os

THRESHOLDS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "score_thresholds.json"
)

# Plausibility bands, widest gap first
SETTLED = "settled"  # no weeks left: nothing can change
NEVER_OBSERVED = "never_observed"
BEYOND_P99 = "beyond_p99"
LIVE_RACE = "live_race"


def load_thresholds(path=THRESHOLDS_PATH):
    with open(path) as handle:
        return json.load(handle)


def _row_for(weeks_remaining, thresholds):
    """Thresholds for N weeks left, falling back to the widest window we have."""
    by_weeks = thresholds["by_weeks_remaining"]
    if not by_weeks:
        return None
    available = sorted(int(k) for k in by_weeks)
    key = min(max(weeks_remaining, available[0]), available[-1])
    return by_weeks[str(key)]


def plausibility(gap, weeks_remaining, thresholds):
    """Classify a points gap as never-observed, beyond-p99, or a live race.

    With no weeks left there is nothing left to score, so no gap can close --
    every verdict is final and no swing is possible.
    """
    if weeks_remaining <= 0:
        return SETTLED
    row = _row_for(weeks_remaining, thresholds)
    if row is None:
        return LIVE_RACE
    if gap > row["max_observed"]:
        return NEVER_OBSERVED
    if gap > row["p99"]:
        return BEYOND_P99
    return LIVE_RACE


def describe(tiebreak, weeks_remaining, thresholds, eliminated=False):
    """One clause qualifying a clinched/eliminated verdict, or None.

    `tiebreak` is {"rival": name, "gap": points} as attached by
    playoff_math.attach_dependencies.
    """
    if not tiebreak:
        return None

    rival = tiebreak["rival"]
    gap = tiebreak["gap"]
    band = plausibility(gap, weeks_remaining, thresholds)
    if band == SETTLED:
        # The season is over; the tiebreaker has already been settled, so there
        # is no dependency left to warn about.
        return None
    row = _row_for(weeks_remaining, thresholds)
    final = "the final week" if weeks_remaining == 1 else f"the final {weeks_remaining} weeks"
    left = "1 week" if weeks_remaining == 1 else f"{weeks_remaining} weeks"

    if band == NEVER_OBSERVED:
        return (
            f"barring a {gap:.0f}-point swing against {rival} in {final} "
            f"— the largest on record in this league is {row['max_observed']:.0f}"
        )
    if band == BEYOND_P99:
        return (
            f"unless {gap:.0f} points swing against {rival} in {final} "
            f"— beyond this league's 99th percentile of {row['p99']:.0f}"
        )
    return (
        f"live points race with {rival} — {gap:.0f} apart with {left} to play"
    )


def qualifies_headline(tiebreak, weeks_remaining, thresholds):
    """True when the swing is ordinary enough that the bare verdict overstates it.

    A 300-point gap is a footnote. A 49-point gap with a week to play is not --
    a team "eliminated" by that margin has a real path, and saying only
    "Eliminated" would be the same kind of overclaim this module exists to stop.
    """
    if not tiebreak:
        return False
    return plausibility(tiebreak["gap"], weeks_remaining, thresholds) == LIVE_RACE
